version: '3'

services:
  # PHP-FPM service for Laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: michelintyre_laravel_app
    volumes:
      - ./projects:/var/www
    ports: 
      - "9000:9000"
    networks:
      - laravel_app_network

  nginx:
    image: nginx:latest
    container_name: michelintyre_nginx_server
    ports:
      - "84:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./projects:/var/www
      - ./nginx/logs:/var/log/nginx
    networks:
      - laravel_app_network

  mariadb:
    image: mariadb:10.11.6
    container_name: michelintyre_mariadb_server
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: waybeo_michelintyre
      MYSQL_USER: michelintyre_user
      MYSQL_PASSWORD: michelintyre_password
    ports:
      - "3309:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - laravel_app_network

  mongodb:
    image: mongo:latest
    container_name: michelintyre_mongodb_server
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root_password
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - laravel_app_network
    command: mongod --auth
    restart: unless-stopped

volumes:
  mariadb_data:
  mongodb_data:

networks:
  laravel_app_network:
    driver: bridge
