version: '3'

services:
  # PHP-FPM service for Laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thomascook_laravel_app # @todo: update container name relate to the project name
    volumes:
      - ./projects:/var/www # @todo: make sure before : file/dir exist
    ports:
      - "9000:9000" # [Accessable ports by application] (Outside:Inside)
    networks:
      - laravel_app_network

  nginx:
    image: nginx:latest
    container_name: thomascook_nginx_server # @todo: update container name relate to the project name
    ports:
      - "84:80" # [Accessable ports by application] (Outside:Inside)
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # @todo: make sure before : file/dir exist
      - ./projects:/var/www # @todo: make sure before : file/dir exist
      - ./nginx/logs:/var/log/nginx # @todo: make sure before : file/dir exist
    networks:
      - laravel_app_network

  mysql:
    image: mysql:5.6
    container_name: thomascook_mysqldb_server # @todo: update container name relate to the project name
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: waybeo_thomascook
      MYSQL_USER: thomascook_user
      MYSQL_PASSWORD: thomascook_password
    ports:
      - "3309:3306" # [Accessable ports by application] (Outside:Inside)
    volumes:
      - mysqldb_data:/var/lib/mysql # @todo: make sure before : file/dir exist
    networks:
      - laravel_app_network

  mongodb:
    image: mongo:2.6
    container_name: thomascook_mongodb_server # @todo: update container name relate to the project name
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root_password
    ports:
      - "27018:27017" # [Accessable ports by application] (Outside:Inside)
    volumes:
      - mongodb_data:/data/db # @todo: make sure before : file/dir exist
    networks:
      - laravel_app_network
    command: mongod
    restart: unless-stopped

volumes:
  mysqldb_data:
  mongodb_data:


networks:
  laravel_app_network:
    driver: bridge
